// ============================================================================
// EN FORMA — Base de datos de alimentos por INTERCAMBIOS
// ----------------------------------------------------------------------------
// Modelo:
//  - category: 'HC' | 'PROT' | 'GRASA' | 'MIX_HC' | 'MIX_GRASA'
//      MIX_HC    = ½ Proteína + ½ Hidratos
//      MIX_GRASA = ½ Proteína + ½ Grasa
//  - mode: 'OMNIVORO' | 'VEGANO' | 'SIN_PESAR'
//      OMNIVORO / VEGANO = pesado en gramos/ml (1 intercambio = la porción)
//      SIN_PESAR        = mismas equivalencias en medidas caseras
//  - label: texto VERBATIM de la porción que equivale a 1 intercambio.
//
// Reglas de negocio:
//  - Verduras y cualquier alimento NO listado / sin categoría = LIBRE (no cuenta).
//  - El coach define qué modo(s) ve cada cliente. Si habilita uno solo, el
//    cliente solo ve ese; si habilita varios, el cliente elige.
//  - Las frutas cuentan como HC.
// ============================================================================

export type FoodCategory = 'HC' | 'PROT' | 'GRASA' | 'MIX_HC' | 'MIX_GRASA';
export type DietMode = 'OMNIVORO' | 'VEGANO' | 'SIN_PESAR';

export interface ExchangeFood {
  mode: DietMode;
  category: FoodCategory;
  label: string; // 1 intercambio = este texto
}

export const SYSTEM_FOODS: ExchangeFood[] = [
  // ==========================================================================
  // MODO 1 · OMNÍVORO (pesado en gramos)
  // ==========================================================================

  // --- HIDRATOS DE CARBONO ---
  { mode: 'OMNIVORO', category: 'HC', label: '150g patata (cruda o cocida)' },
  { mode: 'OMNIVORO', category: 'HC', label: '120g boniato' },
  { mode: 'OMNIVORO', category: 'HC', label: '60g yuca' },
  { mode: 'OMNIVORO', category: 'HC', label: '30g arroz, pasta, couscous o quinoa' },
  { mode: 'OMNIVORO', category: 'HC', label: '63g vasito de arroz o quinoa (medio vasito de 125g)' },
  { mode: 'OMNIVORO', category: 'HC', label: '30g harinas (excepto de almendra)' },
  { mode: 'OMNIVORO', category: 'HC', label: '30g papilla de cereales sin azúcares añadidos' },
  { mode: 'OMNIVORO', category: 'HC', label: '30g cereales (corn flakes, muesli, copos...)' },
  { mode: 'OMNIVORO', category: 'HC', label: '30g maíz para palomitas' },
  { mode: 'OMNIVORO', category: 'HC', label: '40g pan (de molde, tostado, con o sin semillas...)' },
  { mode: 'OMNIVORO', category: 'HC', label: '60g gnocchi' },
  { mode: 'OMNIVORO', category: 'HC', label: '25g tortitas de arroz o maíz (tres tortitas)' },
  { mode: 'OMNIVORO', category: 'HC', label: '35g tortillas para fajitas pequeñas (1 tortilla)' },
  { mode: 'OMNIVORO', category: 'HC', label: '40g tortillas tipo wrap grandes (media tortilla)' },
  { mode: 'OMNIVORO', category: 'HC', label: '35g base para pizza (un cuarto de base)' },
  { mode: 'OMNIVORO', category: 'HC', label: '25g azúcar, dextrosa, amilopectina, ciclodextrina...' },
  { mode: 'OMNIVORO', category: 'HC', label: '40g mermelada (la que sea)' },
  { mode: 'OMNIVORO', category: 'HC', label: '30g miel' },
  { mode: 'OMNIVORO', category: 'HC', label: '30g frutas deshidratadas (pasas, ciruelas...)' },
  { mode: 'OMNIVORO', category: 'HC', label: '35g dátiles' },
  { mode: 'OMNIVORO', category: 'HC', label: '50g castañas ya peladas' },
  { mode: 'OMNIVORO', category: 'HC', label: '300g melón o sandía' },
  { mode: 'OMNIVORO', category: 'HC', label: '230g paraguayo o melocotón' },
  { mode: 'OMNIVORO', category: 'HC', label: '200g frutos rojos (frescos o congelados)' },
  { mode: 'OMNIVORO', category: 'HC', label: '200g ciruela' },
  { mode: 'OMNIVORO', category: 'HC', label: '200g piña en su jugo' },
  { mode: 'OMNIVORO', category: 'HC', label: '150g uvas' },
  { mode: 'OMNIVORO', category: 'HC', label: '150g caquis' },
  { mode: 'OMNIVORO', category: 'HC', label: '100g plátano (uno pequeño)' },
  { mode: 'OMNIVORO', category: 'HC', label: '1 manzana o 1 pera' },
  { mode: 'OMNIVORO', category: 'HC', label: '2 mandarinas o 2 kiwis' },
  { mode: 'OMNIVORO', category: 'HC', label: '130g guisantes frescos o en lata' },
  { mode: 'OMNIVORO', category: 'HC', label: '130g maíz en lata' },
  { mode: 'OMNIVORO', category: 'HC', label: '400g judía verde, alcachofa, menestra, espárragos...' },
  { mode: 'OMNIVORO', category: 'HC', label: '300g pimientos en bote' },
  { mode: 'OMNIVORO', category: 'HC', label: '125g yogurt natural azucarado (1 yogurt)' },
  { mode: 'OMNIVORO', category: 'HC', label: '200ml bebida de arroz, avena, arroz y coco...' },
  { mode: 'OMNIVORO', category: 'HC', label: '250ml bebida de arroz sin azúcares añadidos Hacendado' },
  { mode: 'OMNIVORO', category: 'HC', label: '200ml bebida de avena sin azúcares añadidos Hacendado' },
  { mode: 'OMNIVORO', category: 'HC', label: '140ml bebida de soja sabor chocolate NO Hacendado' },
  { mode: 'OMNIVORO', category: 'HC', label: '200ml zumo comercial' },
  { mode: 'OMNIVORO', category: 'HC', label: '500ml zumo comercial sin azúcares añadidos' },

  // --- PROTEÍNAS ---
  { mode: 'OMNIVORO', category: 'PROT', label: '30g proteína en polvo (whey, iso, vegetal, caseína)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '120g pescado blanco (merluza, bacalao, lubina...)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '120g cefalópodos (pulpo, calamar, sepia...)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '120g mejillones al natural (2 latas)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '100g atún claro al natural (2 latas)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '100g atún en escabeche blanco (2 latas)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '100g carne blanca sin piel (pollo, pavo...)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '80g carne roja magra (sin grasa)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '80g hígado' },
  { mode: 'OMNIVORO', category: 'PROT', label: '50g lomo embuchado' },
  { mode: 'OMNIVORO', category: 'PROT', label: '30g soja texturizada' },
  { mode: 'OMNIVORO', category: 'PROT', label: '200ml claras de huevo (6-7 claras)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '80g seitán' },
  { mode: 'OMNIVORO', category: 'PROT', label: '220g queso fresco batido 0%' },
  { mode: 'OMNIVORO', category: 'PROT', label: '150g queso fresco tipo Burgos (2 tarrinas pequeñas)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '140g requesón 0%' },
  { mode: 'OMNIVORO', category: 'PROT', label: '120g queso cottage light' },
  { mode: 'OMNIVORO', category: 'PROT', label: '1 yogurt YoPro Danone (no choco)' },
  { mode: 'OMNIVORO', category: 'PROT', label: '180g (1 y medio) yogurt +proteínas (no choco no vainilla)' },

  // --- GRASAS ---
  { mode: 'OMNIVORO', category: 'GRASA', label: '10ml (1 cuchara) aceite (preferible AOVE)' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '60g aceitunas (verdes, negras o rellenas)' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '60g aguacate o guacamole' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '18g pipas o semillas (girasol, lino, calabaza, chía)' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '15g frutos secos sin freír (cualquier fruto seco)' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '15g de crema de frutos secos (cacahuete, pistacho, almendras...)' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '15g harina de almendra' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '15g coco rallado (o harina)' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '30g coco natural' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '30g cacao puro desgrasado en polvo' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '20g chocolate +72% (2 onzas)' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '15g mantequilla' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '25g mantequilla ligera' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '20g margarina' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '30g margarina ligera' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '50g nata para cocinar' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '30g nata para montar' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '15g mayonesa' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '30g mayonesa ligera' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '200ml gazpacho' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '50g tomate frito receta artesana Hacendado' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '130g tomate frito comercial' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '100g tomate frito estilo casero' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '80g yogurt griego natural' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '600ml bebida de almendras sin azúcar' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '400ml bebida de almendras Eco-Cesta' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '350ml bebida de almendras Alpro o Hacendado' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '250ml bebida de avellana' },
  { mode: 'OMNIVORO', category: 'GRASA', label: '200ml bebida de avellana y arroz Hacendado' },

  // --- ½ PROTEÍNA + ½ HIDRATOS ---
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '100g legumbre cocida' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '30g legumbre en seco' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '30g pasta de legumbre' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '300ml leche desnatada' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '230ml leche desnatada +proteínas Hacendado' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '250ml leche semidesnatada' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '180ml leche semidesnatada +proteínas Hacendado' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '250g kéfir sin grasa' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '170g yogurt griego desnatado 0%' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '1 yogurt natural (125-140g)' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '2 yogures naturales desnatados 0% (2 de 125g)' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '1 yogurt +proteínas chocolate o vainilla (120g)' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '160g yogurt alto en proteínas Pastoret' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '1 yogurt YoPro chocolate Danone' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '150g yogurt mango sin azúcares añadidos Alpro' },
  { mode: 'OMNIVORO', category: 'MIX_HC', label: '30g levadura de cerveza' },

  // --- ½ PROTEÍNA + ½ GRASA ---
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '30g queso (curado, semicurado, cabra, mozzarella...)' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '60g mozzarella light o feta light' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '1 huevo grande o 2 pequeños' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '70g carne roja grasa (cordero)' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '50g jamón serrano' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '65g pescado azul' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '60g salmón ahumado' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '50g anchoas en conserva' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '60g (1 lata) atún o sardinas en aceite' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '1 lata grande o 2 pequeñas de mejillones en escabeche' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '1 lata de calamares en su tinta o salsa americana' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '55g tempeh' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '100g tofu magro (menos de 115kcal a los 100g)' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '65g tofu graso (más de 115kcal a los 100g)' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '70g heura (bocados, picada, merluza)' },
  { mode: 'OMNIVORO', category: 'MIX_GRASA', label: '50g heura (albóndigas, nuggets)' },

  // ==========================================================================
  // MODO 2 · VEGANO (pesado en gramos)
  // ==========================================================================

  // --- HIDRATOS DE CARBONO ---
  { mode: 'VEGANO', category: 'HC', label: '150g patata (cruda o cocida)' },
  { mode: 'VEGANO', category: 'HC', label: '120g boniato' },
  { mode: 'VEGANO', category: 'HC', label: '60g yuca' },
  { mode: 'VEGANO', category: 'HC', label: '30g arroz, pasta, couscous o quinoa' },
  { mode: 'VEGANO', category: 'HC', label: '63g vasito de arroz o quinoa (medio vasito de 125g)' },
  { mode: 'VEGANO', category: 'HC', label: '30g harinas (excepto de almendra)' },
  { mode: 'VEGANO', category: 'HC', label: '30g papilla de cereales sin azúcares añadidos' },
  { mode: 'VEGANO', category: 'HC', label: '30g cereales (corn flakes, muesli, copos...)' },
  { mode: 'VEGANO', category: 'HC', label: '30g maíz para palomitas' },
  { mode: 'VEGANO', category: 'HC', label: '40g pan (de molde, tostado, con o sin semillas...)' },
  { mode: 'VEGANO', category: 'HC', label: '60g gnocchi' },
  { mode: 'VEGANO', category: 'HC', label: '25g tortitas de arroz o maíz (tres tortitas)' },
  { mode: 'VEGANO', category: 'HC', label: '35g tortillas para fajitas pequeñas (1 tortilla)' },
  { mode: 'VEGANO', category: 'HC', label: '40g tortillas tipo wrap grandes (media tortilla)' },
  { mode: 'VEGANO', category: 'HC', label: '35g base para pizza (un cuarto de base)' },
  { mode: 'VEGANO', category: 'HC', label: '25g azúcar, dextrosa, amilopectina, ciclodextrina...' },
  { mode: 'VEGANO', category: 'HC', label: '40g mermelada (la que sea)' },
  { mode: 'VEGANO', category: 'HC', label: '30g frutas deshidratadas (pasas, ciruelas...)' },
  { mode: 'VEGANO', category: 'HC', label: '35g dátiles' },
  { mode: 'VEGANO', category: 'HC', label: '50g castañas ya peladas' },
  { mode: 'VEGANO', category: 'HC', label: '300g melón o sandía' },
  { mode: 'VEGANO', category: 'HC', label: '230g paraguayo o melocotón' },
  { mode: 'VEGANO', category: 'HC', label: '200g frutos rojos (frescos o congelados)' },
  { mode: 'VEGANO', category: 'HC', label: '200g ciruela' },
  { mode: 'VEGANO', category: 'HC', label: '200g piña en su jugo' },
  { mode: 'VEGANO', category: 'HC', label: '150g uvas' },
  { mode: 'VEGANO', category: 'HC', label: '150g caquis' },
  { mode: 'VEGANO', category: 'HC', label: '100g plátano (uno pequeño)' },
  { mode: 'VEGANO', category: 'HC', label: '1 manzana o 1 pera' },
  { mode: 'VEGANO', category: 'HC', label: '2 mandarinas o 2 kiwis' },
  { mode: 'VEGANO', category: 'HC', label: '130g guisantes frescos o en lata' },
  { mode: 'VEGANO', category: 'HC', label: '130g maíz en lata' },
  { mode: 'VEGANO', category: 'HC', label: '400g judía verde, alcachofa, menestra, espárragos...' },
  { mode: 'VEGANO', category: 'HC', label: '300g pimientos en bote' },
  { mode: 'VEGANO', category: 'HC', label: '200ml bebida de arroz, avena, arroz y coco...' },
  { mode: 'VEGANO', category: 'HC', label: '250ml bebida de arroz sin azúcares añadidos Hacendado' },
  { mode: 'VEGANO', category: 'HC', label: '200ml bebida de avena sin azúcares añadidos Hacendado' },
  { mode: 'VEGANO', category: 'HC', label: '140ml bebida de soja sabor chocolate NO Hacendado' },
  { mode: 'VEGANO', category: 'HC', label: '200ml zumo comercial' },
  { mode: 'VEGANO', category: 'HC', label: '500ml zumo comercial sin azúcares añadidos' },

  // --- PROTEÍNAS ---
  { mode: 'VEGANO', category: 'PROT', label: '30g soja texturizada' },
  { mode: 'VEGANO', category: 'PROT', label: '80g seitán' },

  // --- GRASAS ---
  { mode: 'VEGANO', category: 'GRASA', label: '10ml (1 cuchara) aceite (preferible AOVE)' },
  { mode: 'VEGANO', category: 'GRASA', label: '60g aceitunas (verdes, negras o rellenas)' },
  { mode: 'VEGANO', category: 'GRASA', label: '60g aguacate o guacamole' },
  { mode: 'VEGANO', category: 'GRASA', label: '18g pipas o semillas (girasol, lino, calabaza, chía)' },
  { mode: 'VEGANO', category: 'GRASA', label: '15g frutos secos sin freír (cualquier fruto seco)' },
  { mode: 'VEGANO', category: 'GRASA', label: '15g de crema de frutos secos (cacahuete, pistacho, almendras...)' },
  { mode: 'VEGANO', category: 'GRASA', label: '15g harina de almendra' },
  { mode: 'VEGANO', category: 'GRASA', label: '15g coco rallado (o harina)' },
  { mode: 'VEGANO', category: 'GRASA', label: '30g coco natural' },
  { mode: 'VEGANO', category: 'GRASA', label: '30g cacao puro desgrasado en polvo' },
  { mode: 'VEGANO', category: 'GRASA', label: '20g chocolate +72% (2 onzas)' },
  { mode: 'VEGANO', category: 'GRASA', label: '20g margarina' },
  { mode: 'VEGANO', category: 'GRASA', label: '30g margarina ligera' },
  { mode: 'VEGANO', category: 'GRASA', label: '200ml gazpacho' },
  { mode: 'VEGANO', category: 'GRASA', label: '50g tomate frito receta artesana Hacendado' },
  { mode: 'VEGANO', category: 'GRASA', label: '130g tomate frito comercial' },
  { mode: 'VEGANO', category: 'GRASA', label: '100g tomate frito estilo casero' },
  { mode: 'VEGANO', category: 'GRASA', label: '600ml bebida de almendras sin azúcar' },
  { mode: 'VEGANO', category: 'GRASA', label: '400ml bebida de almendras Eco-Cesta' },
  { mode: 'VEGANO', category: 'GRASA', label: '350ml bebida de almendras Alpro o Hacendado' },
  { mode: 'VEGANO', category: 'GRASA', label: '250ml bebida de avellana' },
  { mode: 'VEGANO', category: 'GRASA', label: '200ml bebida de avellana y arroz Hacendado' },

  // --- ½ PROTEÍNA + ½ HIDRATOS ---
  { mode: 'VEGANO', category: 'MIX_HC', label: '100g legumbre cocida' },
  { mode: 'VEGANO', category: 'MIX_HC', label: '30g legumbre en seco' },
  { mode: 'VEGANO', category: 'MIX_HC', label: '30g pasta de legumbre' },
  { mode: 'VEGANO', category: 'MIX_HC', label: '30g levadura de cerveza' },

  // --- ½ PROTEÍNA + ½ GRASA ---
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '300ml bebida de soja sin azúcares añadidos' },
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '200g yogurt de soja natural' },
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '55g tempeh' },
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '100g tofu magro (menos de 115kcal a los 100g)' },
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '65g tofu graso (más de 115kcal a los 100g)' },
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '70g heura (bocados, picada, merluza)' },
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '50g heura (albóndigas, nuggets)' },
  { mode: 'VEGANO', category: 'MIX_GRASA', label: '80g Beyond Burger' },

  // ==========================================================================
  // MODO 3 · SIN PESAR (medidas caseras)
  // ==========================================================================

  // --- HIDRATOS DE CARBONO ---
  { mode: 'SIN_PESAR', category: 'HC', label: 'Patata → 1 patata mediana del tamaño de un puño' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Boniato → 1 boniato pequeño' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Yuca → 1 trozo del tamaño de media palma' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Arroz integral, quinoa (crudos) → 3 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Pasta, cuscús (crudos) → 3 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Vasito de arroz o quinoa → medio vasito individual' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Pan (de molde, tostado, con o sin semillas…) → 1 rebanada grande' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Gnocchi → 10–12 unidades' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Tortillas para fajitas pequeñas → 1 tortilla' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Tortillas tipo wrap grandes → media tortilla' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Papilla de cereales sin azúcares añadidos → 3 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Harinas (excepto de almendra) → 3 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Maíz para palomitas (sin hacer) → un cuarto de vaso de granos' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Cereales (corn flakes, muesli, copos…) → 1 vaso pequeño' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Tortitas de arroz o maíz → 3 tortitas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Base para pizza → un cuarto de base' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Castañas ya peladas → 1 puñado mediano' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Dátiles → 2 dátiles grandes' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Frutas deshidratadas (pasas, ciruelas…) → 1 puñado pequeño' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Mermelada → 2 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Miel → 1 cucharada sopera colmada' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Azúcar, dextrosa, amilopectina, ciclodextrina… → 2 cucharadas rasas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Yogur natural azucarado → 1 yogur individual' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Bebida vegetal (arroz, avena, coco...) → 1 vaso' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Bebida de soja sabor chocolate NO Hacendado → medio vaso' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Zumo comercial → 1 vaso pequeño' },
  // FRUTAS (cuentan como HC)
  { mode: 'SIN_PESAR', category: 'HC', label: 'Frutos rojos congelados → 1 bol grande' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Arándanos → 1 vaso pequeño' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Fresas → 1 bol mediano lleno' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Cerezas → 1 bol pequeño (un puñado grande)' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Manzana o pera → 1 unidad mediana' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Kiwis o mandarinas → 2 unidades' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Naranja → 1 unidad mediana' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Ciruela → 2 ciruelas medianas' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Paraguayo o melocotón → 2 unidades pequeñas o 1 grande' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Piña → 2 rodajas gruesas o 1 taza grande de dados' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Mango → 1 taza mediana de dados' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Uvas → 1 bol pequeño (un puñado grande)' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Caquis → 1 unidad pequeña' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Plátano mediano → 1 unidad' },
  { mode: 'SIN_PESAR', category: 'HC', label: 'Sandía o melón → 1 bol grande lleno' },

  // --- PROTEÍNAS ---
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Proteína en polvo (whey, iso, vegetal...) → un cacito' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Pescado blanco (merluza, bacalao, lubina...) → un filete del tamaño de la mano' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Seitán → un bloque del tamaño de la mano' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Mejillones al natural (2 latas)' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Atún claro al natural (2 latas)' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Atún en escabeche blanco (2 latas)' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Carne blanca sin piel (pollo, pavo...) → un filete del tamaño de la mano' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Carne roja magra (sin grasa) → un filete pequeño' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Soja texturizada → 1/2 vaso' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Claras de huevo (6-7 claras)' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Queso fresco batido 0% → 220g' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Queso fresco tipo Burgos (2 tarrinas pequeñas)' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Requesón 0% (2 tarrinas pequeñas)' },
  { mode: 'SIN_PESAR', category: 'PROT', label: '1 yogurt YoPro Danone (no choco)' },
  { mode: 'SIN_PESAR', category: 'PROT', label: 'Yogurt +proteínas (no choco no vainilla) → 2 yogures' },

  // --- GRASAS ---
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Aceite (preferible AOVE) → 1 cuchara' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Pipas o semillas (girasol, lino, calabaza, chía) → 1 cucharada sopera colmada' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Frutos secos sin freír → 1 puñado pequeño' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Crema de frutos secos (cacahuete, pistacho, almendra…) → 1 cucharada sopera' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Aceitunas (verdes, negras o rellenas) → 1 puñado pequeño' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Aguacate o guacamole → 2 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Harina de almendra → 2 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Cacao puro desgrasado en polvo → 3 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Gazpacho → 1 vaso lleno' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Tomate frito → 4 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Chocolate +72% → 2 onzas' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Yogur griego natural → medio vasito individual' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Coco rallado (o harina) → 1 cucharada sopera colmada' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Mantequilla → 1 cucharada sopera' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Margarina → 1 cucharada sopera' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Mayonesa → 1 cucharada sopera' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Bebida de almendras sin azúcar → 3 vasos' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Bebida de almendras Eco-Cesta → 2 vasos' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Bebida de almendras Alpro o Hacendado → un vaso y medio' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Bebida de avellana → un vaso' },
  { mode: 'SIN_PESAR', category: 'GRASA', label: 'Bebida de avellana y arroz Hacendado → un vaso' },

  // --- ½ PROTEÍNA + ½ HIDRATOS ---
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Legumbre cocida → 1 vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Legumbre en seco → 3 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Pasta de legumbre → 3 cucharadas soperas' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Leche desnatada → un vaso grande' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Leche desnatada +proteínas Hacendado → un vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Leche semidesnatada → un vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Leche semidesnatada +proteínas Hacendado → medio vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Kéfir sin grasa → un vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Yogur griego desnatado 0% → un vasito' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: '1 yogurt natural' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: '2 yogures naturales desnatados 0%' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: '1 yogurt +proteínas chocolate o vainilla' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Yogurt alto en proteínas Pastoret → medio vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: '1 yogurt YoPro chocolate Danone' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Yogurt mango sin azúcares añadidos Alpro → medio' },
  { mode: 'SIN_PESAR', category: 'MIX_HC', label: 'Levadura de cerveza → 3 cucharadas' },

  // --- ½ PROTEÍNA + ½ GRASA ---
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Leche entera → medio vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Bebida de soja sin azúcares añadidos → un vaso grande' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Yogurt de soja natural → un vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Kéfir natural → un vaso' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Queso (curado, semicurado, cabra, mozzarella...) → 2 triángulos' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Mozzarella light o feta light → 3 lonchas' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: '1 huevo grande o 2 pequeños' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Carne roja grasa (cordero) → una pieza pequeña' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Embutido de calidad (jamón serrano, lomo...) → 3–4 lonchas finas' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Pescado azul → un filete pequeño' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Mejillones en escabeche → 1 lata grande o 2 pequeñas' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Anchoas en conserva → 1 lata pequeña' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Atún o sardinas en aceite → 1 lata pequeña' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Calamares en su tinta o salsa americana → 1 lata' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Tempeh → medio bloque (pequeño)' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Tofu magro → medio bloque' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Tofu graso → medio bloque (pequeño)' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Heura (bocados, picada, merluza) → medio blister' },
  { mode: 'SIN_PESAR', category: 'MIX_GRASA', label: 'Albóndigas/nuggets de Heura → dos o tres piezas' },
];
